source "https://rubygems.org"

gem "less", "~> 2.2.2"
gem "middleman", "~> 4.3.7"
gem "middleman-minify-html", "~> 3.3.0"
gem "rack-contrib", "~> 1.1.0"
gem "redcarpet", "~> 2.2.2"
gem "therubyracer", "~> 0.10.2"
gem "thin", "~> 1.5.0"

group :development do
  gem "highline", "~> 1.6.15"
end
