source 'https://rubygems.org'

gem "less", "~> 2.2.2"
gem "middleman", "~> 3.1.0"
gem "middleman-minify-html", "~> 3.3.0"
gem "rack-contrib", "~> 1.2.0"
gem "redcarpet", "~> 2.2.2"
gem "therubyracer", "~> 0.10.2"
gem "thin", "~> 1.5.1"

group :development do
  gem "highline", "~> 1.6.15"
end
